version: "3.9"  # optional since v1.27.0
services:
  mongodb_container:
    image: mongo:latest
    volumes:
      - mongodb_data_container:/data/db

  gas_scanner_container:
    image: gas_scanner
    environment:
      PROVIDER_ADDRESS: https://bor.golem.network
      MONGO_DB_CONNECTION_STRING: mongodb://mongodb_container:27017
      MONGO_DB_NAME: GasUsage
    tty: true

volumes:
  mongodb_data_container:
 
