services:
  gas_scanner_next:
    build: .
    image: gas-scanner-next
    container_name: gas_scanner_next
    environment:
      PROVIDER_ADDRESS: https://bor.golem.network
    ports:
      - "3000:3000"
    tty: true